### ISSUE TITLE
Unexpected version showed in search

### ISSUE THREAD

**Issue by rconde01** [conan-io/web#61]
- I searched for `yaml-cpp`
- The result showed "Last updated version 0.6.3"
- clicking through shows `yaml-cpp/0.6.3` but then underneath "0.7.0, 0.6.3"

Seems like it should give you the latest version by default

**Comment by daniel-heater-imprivata** [comment]
Seeing the same issue with Qt, showing latest as 5.15.9, but latest under the versions tab is 6.5.1

**Comment by davidsanfal** [comment]
Hi @rconde01 @daniel-heater-imprivata ! the information that appears is correct, it is the latest **updated** version in conancenter, but it is being understood as the latest version **published**. In some cases it is showing a version that is not the latest, because it has been processed after the newest one or there have been only changes for that old version.

We understand the issue because it is not the value that is expected in this type of searches and we are already working to update this field and show the expected information.

Thank you for your feedback!

**Comment by davidsanfal** [comment]
Hi!

We have already deployed the feature to show the `last version` instead of the `last updated version`.

<img width="1214" alt="Screenshot 2023-08-07 at 15 15 58" src="https://github.com/conan-io/web/assets/5907894/53c7d1f5-4af2-4ef8-be90-261240e2d264">
<img width="1161" alt="Screenshot 2023-08-07 at 15 17 01" src="https://github.com/conan-io/web/assets/5907894/43b9bfb6-1717-45ef-be4a-562e3b973de3">
