### ISSUE TITLE
conan center used to provide useful information

### ISSUE THREAD

**Issue by lederernc** [conan-io/web#62]
all the useful information is now gone.

how do I search for recipe revisions in chronological order?

**Comment by memsharded** [comment]
Hi @lederernc 

It would be useful to know what is the use case to search for recipe revision in chronological order in the web site.

The Conan client provide all the necessary tools like ``conan list zlib/1.2.13#* -r=conancenter`` to display that information, with the added advantage that it allows listing the revision in the same way for your own private repositories. This is the recommended way to list revisions in chronological order. It also has the ``--format=json`` output for convenient json output for automation.

We are willing to learn about the use cases in which this information is useful in the way, as we see the web site as a "discovery" site, to learn about the existence of a given library and version like ``zlib/1.2.13``, but knowing the history of revisions via web seems an advanced use case that belongs to the client tool.

**Comment by santhonisz** [comment]
Hi @memsharded 

I totally understand with what you are saying re the Conan client providing the necessary tools to discover more information about Conan Center packages; however would a possible enhancement to the web site be to provide example command(s) for the given recipe that users can quickly copy/paste to then run themselves to do just that e.g.

```bash
# All recipe revisions
conan list zlib/1.2.13#* -r=conancenter
# HTML view of all packages for latest recipe revision:
conan list zlib/1.2.13:* -r=conancenter -f=html > zlib_conancenter_packages.html
# HTML view of all packages for all recipe revisions:
conan list zlib/1.2.13#*:* -r=conancenter -f=html > zlib_conancenter_packages.html
```

**Comment by memsharded** [comment]
Yes, @santhonisz I think this could be a good idea and make sense, thanks very much for the suggestion!

**Comment by saierd** [comment]
I used the combobox with the different recipe revisions on the old website to scroll through the different conanfiles and choose one that is compatible with my old version of conan. This is much harder now, since you cannot see the different conanfiles at a glance anymore.

**Comment by lederernc** [comment]
> Hi @memsharded
> 
> I totally understand with what you are saying re the Conan client providing the necessary tools to discover more information about Conan Center packages; however would a possible enhancement to the web site be to provide example command(s) for the given recipe that users can quickly copy/paste to then run themselves to do just that e.g.
> 
> ```shell
> # All recipe revisions
> conan list zlib/1.2.13#* -r=conancenter
> # HTML view of all packages for latest recipe revision:
> conan list zlib/1.2.13:* -r=conancenter -f=html > zlib_conancenter_packages.html
> # HTML view of all packages for all recipe revisions:
> conan list zlib/1.2.13#*:* -r=conancenter -f=html > zlib_conancenter_packages.html
> ```

```conan list boost/1.79.0#* -r=conancenter
WARN: Migration: Updating settings.yml
Migration: Settings already up to date
'list' is not a Conan command. See 'conan --help'.

ERROR: Unknown command 'list'```

**Comment by memsharded** [comment]
``conan list`` is a Conan 2.0 command, that has been out in beta for 1 year, and released since February: https://docs.conan.io/2/changelog.html

**Comment by jcar87** [comment]
> I used the combobox with the different recipe revisions on the old website to scroll through the different conanfiles and choose one that is compatible with my old version of conan. This is much harder now, since you cannot see the different conanfiles at a glance anymore.

Hi @saierd  - thank you for your feedback. If you could provide more details about the version of Conan you are using and the reasons this is not a recent version, that would be appreciated, so that we can understand the use case.
Conan Center pushes to use recent versions of Conan. While we do indeed recommend relying on revisions (via lockfiles) to retain reproducibility and protect from breaking changes in an "unpredicted" way - we do expect that when revisions are eventually updated to a newer one, that this is the most recent at the time of doing so. Is this not the case? we put a lot of  effort in keeping Conan backwards compatible (for the same major release), and if there is ever a regression, it is treated as a bug that requires an urgent fix. So I would also like to understand the scenarios in which updating Conan itself is not possible.

**Comment by saierd** [comment]
Updating Conan is probably possible. In fact it seems like it is possible to install Conan 1.60 even on my ancient Ubuntu 14.04 Docker image with Python 3.6, which is nice :+1:.

So far it was not necessary, though. There is usually no real need for us to update dependencies. Most of the time we just want to add a new dependency to a single package or maybe sometimes update a single package. In this case it was always much easier and less risky to simply go to conan center and select a recipe revision for this single package that is compatible with the existing Conan version instead of taking the risk to break anything by updating build tools.

**Comment by davidsanfal** [comment]
Hi @ftena! this is one of the improvements we are already working on, we want to deploy it as soon as we have it finished.
We will let you know in this ticket when it is available. Thank you for the feedback!

**Comment by davidsanfal** [comment]
Hi @ftena! We have added a new tab with the packages info for the selected version. [boost/1.83.0 example](https://conan.io/center/recipes/boost?version=1.83.0).

It also allows you to filter packages by OS and architecture using the "available packages" buttons.

If you look at the web right now, you might see recipes without this information, I am writing you while we are populating the new data 🚀, but the example I am giving you is a very complete example with all the new features.

<img width="1349" alt="Screenshot 2023-09-26 at 20 17 16" src="https://github.com/conan-io/web/assets/5907894/af4dcf2f-07b0-4360-8526-479aa4bbf19d">


<img width="1301" alt="Screenshot 2023-09-26 at 20 17 26" src="https://github.com/conan-io/web/assets/5907894/98ae0555-ce29-49e1-8afd-067a596b6f1f">

**Comment by lederernc** [comment]
that is wonderful!

**Comment by ftena** [comment]
> Hi @ftena! We have added a new tab with the packages info for the selected version. [boost/1.83.0 example](https://conan.io/center/recipes/boost?version=1.83.0).
> 
> It also allows you to filter packages by OS and architecture using the "available packages" buttons.
> 
> If you look at the web right now, you might see recipes without this information, I am writing you while we are populating the new data 🚀, but the example I am giving you is a very complete example with all the new features.
> 
> <img alt="Screenshot 2023-09-26 at 20 17 16" width="1349" src="https://user-images.githubusercontent.com/5907894/270756088-af4dcf2f-07b0-4360-8526-479aa4bbf19d.png"> <img alt="Screenshot 2023-09-26 at 20 17 26" width="1301" src="https://user-images.githubusercontent.com/5907894/270756089-98ae0555-ce29-49e1-8afd-067a596b6f1f.png">

Wow. You are an amazing team, guys.

Thanks for your effort and commitment!

conan FTW!
