### ISSUE TITLE
Search packages by tags

### ISSUE THREAD

**Issue by VL-Impact** [conan-io/web#69]
As of now, packages have some tags assigned to them, but those have just informative purpose, and thus not very useful.

I would like to have ability to search packages with specific tag(s).

For instance, see intx package below:

![Tags](https://github.com/conan-io/web/assets/2428115/ad2d97ff-223d-435a-a221-b8d843272dfa)

It has tag #biginteger - I would like to click on it and see other packages that implement extended precision arithmetic (now it is just inactive element on page).

More even, if I now enter "biginteger" in search box, I won't find even intx iself.

**Comment by prince-chrismc** [comment]
Being about to select "all" would be super useful because the tags are super inconsistent and have no structure.

Taking testing libraries, I want to generically search for them to get an idea of what exists... however not all of them have "test" in the name and there are 2 dozen + tags that need to be Manually selected

![image](https://github.com/conan-io/web/assets/16867443/c32d50d7-e2f7-49b6-95ac-451c76eaecdc)

***

Another example where there is more then one page

![image](https://github.com/conan-io/web/assets/16867443/63bb98a8-3a1f-4b92-ad70-f907e1da3abf)

**Comment by prince-chrismc** [comment]
It would also be great to sort the tags like dee2db1cbaa6c9e56086e9b758c1bf93da50fb30 :)
