### ISSUE TITLE
always report unable to find xxx in remotes

### ISSUE THREAD

**Issue by zhangjinpeng66** [conan-io/web#86]
![conancenter-1](https://github.com/conan-io/web/assets/6256892/635f72aa-8701-43ab-9ff7-283d5b465aa5)
![conancenter-2](https://github.com/conan-io/web/assets/6256892/5c8c4c85-a365-4159-b883-f0aee9e35e93)
![conancenter-3](https://github.com/conan-io/web/assets/6256892/deb8a214-ba02-43a8-86b9-545f260774ac)
![conancenter-4](https://github.com/conan-io/web/assets/6256892/fbced078-36b3-4f10-98cd-f2c6b667f9ea)

**Comment by zhangjinpeng66** [comment]
The above picture discribe the question for example

**Comment by memsharded** [comment]
Hi @zhangjinpeng66 

Thanks for your report.

I think you are adding the wrong endpoint URL. You are adding https://conan.io/center, but this is not correct, please check:

- https://docs.conan.io/2/reference/config_files/remotes.html
- https://github.com/conan-io/conan-center-index

Also, by default it is not necessary to add the ConanCenter remote, because it comes configured by default. But if you want to add it is:
```
conan remote add conancenter https://center.conan.io
```
Note the API enpoint is ``center.conan.io`` but not ``conan.io/center`` (that is the Web app only)

**Comment by memsharded** [comment]
This has been closed by https://github.com/conan-io/conan/pull/14531, but please don't hesitate to ask if you have any further question, you can also create new tickets.
